#!/usr/bin/env bash
# DesignOps regeneration. Rewrites ONLY product/generated/** from the blueprint.
# It must never write under product/src/** — that's the dev team's (point 7 + 8).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)/product"
GEN="$ROOT/generated"
node - "$GEN" <<'NODE'
const fs = require("fs"), path = require("path");
const gen = process.argv[2];
const bp = JSON.parse(fs.readFileSync(path.join(gen, "blueprints/booking.blueprint.json"), "utf8"));
const BANNER = "// @generated by designops — DO NOT EDIT. Rewritten on every regenerate.\n" +
               `// source: blueprints/booking.blueprint.json\n`;

// 1) contract — a type/shape the dev binding implements (stable seam)
const fields = bp.data_contract.fields;
const checks = Object.entries(fields)
  .map(([k, t]) => `  if (typeof d.${k} !== "${t}") throw new TypeError("BookingData.${k} must be ${t}");`)
  .join("\n");
fs.writeFileSync(path.join(gen, "contracts/booking.mjs"),
`${BANNER}// ${bp.data_contract.name}: ${Object.entries(fields).map(([k,t])=>`${k}:${t}`).join(", ")}
export const ACTIONS = ${JSON.stringify(bp.actions.map(a => a.name))};
export function assertBookingData(d) {
${checks}
  return d;
}
`);

// 2) screen — a UI SHELL only. Layout from regions; submit delegates to injected actions.
const slots = bp.regions.map(r => r.slot);
fs.writeFileSync(path.join(gen, "screens/booking.mjs"),
`${BANNER}import { ACTIONS } from "../contracts/booking.mjs";
// layout regions are regenerated from the blueprint; the shell holds NO business logic.
export function createBookingScreen({ actions }) {
  for (const name of ACTIONS) if (typeof actions?.[name] !== "function")
    throw new Error("missing action: " + name);
  return {
    layout: ${JSON.stringify(slots)},
    submit: (data) => actions.submitBooking(data),   // delegates to the dev binding
  };
}
`);
console.log("regenerated: contracts/booking.mjs, screens/booking.mjs (src/ untouched)");
NODE
